# https://home-assistant.io/blog/2016/08/03/laundry-automation-update/
sensor:
  - platform: mqtt
    name: "Dryer Status"
    state_topic: "sensor/dryer"
    unit_of_measurement: ""

  - platform: mqtt
    name: "Washer Status"
    state_topic: "sensor/washer"
    unit_of_measurement: ""

automation:
  - alias: Washer complete
    trigger:
      platform: state
      entity_id: sensor.washer_status
      from: 'Running'
      to: 'Complete'
    action:
      service: script.turn_on
      entity_id: script.washer_complete

  - alias: Washer emptied
    trigger:
      platform: state
      entity_id: sensor.washer_status
      from: 'Complete'
      to: 'Empty'
    action:
      service: scene.turn_on
      entity_id: scene.normal

script:
  washer_complete:
    alias: Washer Complete
    sequence:
      - alias: Join Notification
        service: notify.join
        data:
          message: "The washing machine has finished its cycle, please empty it!"
      - alias: Living Room Lights Blue
        service: scene.turn_on
        data:
          entity_id: scene.blue
